### ISSUE TITLE
Delete master branch so there's only a gh-pages one

### ISSUE THREAD

**Issue by tjschuck** [pfiller/kristina-filler-dot-com#2]
If you make the gh-pages branch the default and delete the master branch, then PRs like #1 can just be merged from GH and the page will rebuild itself.  [Instructions](http://oli.jp/2011/github-pages-workflow/#deleting-master).

:heart: :heart: :heart_eyes_cat: :heart:

**Comment by pfiller** [comment]
I did it, it's done!
